### ISSUE TITLE
C lib in c++ code

### ISSUE THREAD

**Issue by snowy-shadow** [USSTR-Avionics/MiniRockets#20]
When including `C` libs in c++, add prefix `c` and remove `.h`

e.g.
`#include <cstdlib>` instead of `#include <stdlib.h>`

this applies for all c libs

**Comment by frroossst** [comment]
Can you link me some resources as to why <cstdlib> is preferable. (just to document the reasons)

**Comment by snowy-shadow** [comment]
"the proper way" because everything is now wrapped in the namespace `std`
https://www.incredibuild.com/blog/cstdlib-in-c-explained

`stdlib.h` is deprecated since 1998
https://stackoverflow.com/questions/2900785/whats-the-difference-between-cstdlib-and-stdlib-h

**Comment by frroossst** [comment]
Thanks! :+1:
